owner: reacto11mecha
repo: uptime-status

sites:
  - name: Sekilas 13
    url: https://sekilas13.vercel.app
  - name: WUNO Bot Documentation Site
    url: https://wuno.rmecha.my.id/
  - name: Web Jadwal Pelajaran
    url: https://jadwal.rmecha.my.id/
  - name: My Personal Site
    url: https://rmecha.my.id

status-website:
  cname: status.rmecha.my.id
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pantau Terus
  theme: night
  introTitle: "Website pemantau web penting, powered by **Upptime**"
  introMessage: Website ini memantau web yang sehari-hari digunakan atau web yang penting bagi saya. Data yang dihasilkan merupakan data yang diambil secara **real-time** yang hanya menggunakan Github Action sebagai pengambil datanya. Ditenagai oleh [Upptime](https://github.com/upptime/upptime), pengecek status website menggunakan github action.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
